### ISSUE TITLE
Apply Refactoring

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime.cloud#60]
## ToDo

- [x] Rename `BitFile.java` to `bitfile_controller.java`
- [x] Move `/upload` function to `bitfile_controller.java`
- [x] Rename `/getfile` to `/bitfile`
