### ISSUE TITLE
Add Image Capture to CSV Service

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime.cloud#80]
## Description

Take the image in the CSV Service.

## ToDo

- [x] Add Image capture of IP camera to CSV Service
- [x] Store Image alongside sample
- [x]  Set up Raspberry Pi as IP camera
