### ISSUE TITLE
Remove Twins from Java Implementation

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime.cloud#87]
## ToDo
- [x] Add Tag to last commit with Twins
- [x] Remove Twin implementations from source code
- [x] Refactor Monitor to work directly with device
- [x] Provide basic functionality/status via Monitor for Device
